### ISSUE TITLE
Use `uuid::Uuid` data type with `"serde"` feature.

### ISSUE THREAD

**Issue by brodeuralexis** [cholcombe973/rusix#1]
https://github.com/cholcombe973/rusix/blob/05d4004aef56fabee5f15449044e07cb99125be0/src/lib/config.rs#L19

At this line, it is stated that `Serialize` and `Deserialize` are not implemented for `uuid::Uuid`, and that is true only if the `"serde"` feature is not activated in `Cargo.toml`.

```toml
[dependencies]
uuid = { version = "0.6", features = ["serde", "v4"] }
```
